"""CoChem Bench Engine: Core Scientific Extrapolation & Benchmark Engines (Stages 1.0 - 5.0)."""

from __future__ import annotations

from bench_engine.cochem_bench_cbs import (
    CBSExtrapolationResult,
    DualBasisDispatcher,
    HelgakerExtrapolator,
    ResidualFitAnalyzer,
    SlowConvInterceptionResult,
    SlowConvInterceptor,
    commit_cbs_to_hdf5,
    read_cbs_from_hdf5,
    run_cbs_pipeline,
    CBS_UNCERTAINTY_THRESHOLD_KCAL_MOL,
    PARAMETER_MATRIX,
)
from bench_engine.cochem_bench_cv import (
    CoreValenceMapper,
    CVCorrectionResult,
    DeltaExtractor,
    DualCorrelationEngine,
    commit_cv_to_hdf5,
    read_cv_from_hdf5,
    run_cv_pipeline,
)
from bench_engine.cochem_bench_rel import (
    DeltaRelExtractor,
    RelCorrectionResult,
    RelativisticExecutionError,
    RelativisticHamiltonianInjector,
    RelativisticInputError,
    SpinOrbitCoupler,
    X2CDivergenceError,
    X2CHandler,
    commit_rel_to_hdf5,
    read_rel_from_hdf5,
    run_rel_pipeline,
    DEFAULT_RELATIVISTIC_Z_THRESHOLD,
    HARTREE_TO_KCAL_MOL,
)
from bench_engine.cochem_bench_export import (
    AirGapPackageMissingError,
    AirGapVerifier,
    CompositeAggregator,
    CompositeEnergyRecord,
    ExportPipelineResult,
    HDF5SchemaError,
    LaTeXExportConfig,
    MissingZPVEError,
    PublicationArchiver,
    ProvenanceStamper,
    SiunitxLaTeXCompiler,
    run_export_pipeline,
)

__all__ = [
    # Stage 2.0 CBS
    "DualBasisDispatcher",
    "HelgakerExtrapolator",
    "ResidualFitAnalyzer",
    "SlowConvInterceptor",
    "CBSExtrapolationResult",
    "SlowConvInterceptionResult",
    "commit_cbs_to_hdf5",
    "read_cbs_from_hdf5",
    "run_cbs_pipeline",
    "CBS_UNCERTAINTY_THRESHOLD_KCAL_MOL",
    "PARAMETER_MATRIX",
    # Stage 3.0 CV
    "CoreValenceMapper",
    "DualCorrelationEngine",
    "DeltaExtractor",
    "CVCorrectionResult",
    "commit_cv_to_hdf5",
    "read_cv_from_hdf5",
    "run_cv_pipeline",
    # Stage 4.0 Relativistic & SOC
    "RelativisticHamiltonianInjector",
    "X2CHandler",
    "X2CDivergenceError",
    "RelativisticExecutionError",
    "RelativisticInputError",
    "SpinOrbitCoupler",
    "DeltaRelExtractor",
    "RelCorrectionResult",
    "commit_rel_to_hdf5",
    "read_rel_from_hdf5",
    "run_rel_pipeline",
    "DEFAULT_RELATIVISTIC_Z_THRESHOLD",
    "HARTREE_TO_KCAL_MOL",
    # Stage 5.0 Exporter
    "CompositeAggregator",
    "CompositeEnergyRecord",
    "ExportPipelineResult",
    "SiunitxLaTeXCompiler",
    "LaTeXExportConfig",
    "ProvenanceStamper",
    "AirGapVerifier",
    "PublicationArchiver",
    "MissingZPVEError",
    "AirGapPackageMissingError",
    "HDF5SchemaError",
    "run_export_pipeline",
]
