[pytest]
pythonpath = . src cochem_topos
testpaths = tests/test_cochem_topos_iso_recycle.py
addopts = -v --strict-markers
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
    ignore::RuntimeWarning
