"""Root-level entry point and module wrapper for Telemetry Validation Schemas Subsystem (Task 1.15).

Governed by Method Matrix v4.2, Anti-Spoofing Protocol v4, Mendeleev Dynamic Mass Mandate,
and SRS-CHUNK-018-AG-ML-RL-TRANSITION-V1.0-20260913 (Task 1.15 & FR-04/FR-06).
"""

from __future__ import annotations

from pathlib import Path
import sys

# Ensure src/ is on Python search path
SRC_DIR = Path(__file__).resolve().parent / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from cochem_ml.schemas import (
    ASTDiffVectorSchema,
    AuditTraceQuerySchema,
    ChunkGeometrySpecSchema,
    DAGEdgeSchema,
    DAGNodeSchema,
    DAGVisualizerStateSchema,
    DaemonConfigSchema,
    DaemonTelemetryMetricsSchema,
    DatasetPreallocationSpecSchema,
    DiffASTParseSchema,
    EnergyGradientResidualSchema,
    EntityModificationSchema,
    EpistemicUncertaintyVectorSchema,
    ExecutionTelemetryVectorSchema,
    FileSystemEventSchema,
    FragmentationMetricsSchema,
    FunctionComplexitySchema,
    ImportShiftSchema,
    ImportStatementSchema,
    ImportSummarySchema,
    JSONLDRegistryPayloadSchema,
    ModuleComplexitySchema,
    MultimodalStateVectorSchema,
    PaginatedSliceSchema,
    ParquetBufferConfigSchema,
    ParquetBufferMetricsSchema,
    PhysicalResidualRecordSchema,
    PhysicalResidualVectorSchema,
    PreallocatedStreamerConfigSchema,
    ProcessMemorySnapshotSchema,
    PromptResponseDistributionSchema,
    RAMGuardrailConfigSchema,
    RAMGuardrailMetricsSchema,
    RAMTelemetryRecordSchema,
    RollbackResultSchema,
    RollingWindowStatsSchema,
    RotationalDriftResidualSchema,
    SCFConvergenceResidualSchema,
    StandardizedVectorRecordSchema,
    StandardizerConfigSchema,
    StateVectorRecordSchema,
    StreamedBatchReceiptSchema,
    TaskVectorSchema,
    TelemetryRecordSchema,
    TensorCacheConfigSchema,
    TensorCacheMetricsSchema,
    TensorRecordMetadataSchema,
    TokenEntropyEvaluationSchema,
    TokenEntropySchema,
    TokenLogprobSchema,
    TokenVelocitySchema,
    TreeModificationSchema,
    VisualizerEdgeLayoutSchema,
    VisualizerNodeLayoutSchema,
    compute_sha256_digest,
    verify_mendeleev_integrity,
)

__all__ = [
    "verify_mendeleev_integrity",
    "compute_sha256_digest",
    "TelemetryRecordSchema",
    "FileSystemEventSchema",
    "ImportStatementSchema",
    "ImportShiftSchema",
    "ImportSummarySchema",
    "FunctionComplexitySchema",
    "ModuleComplexitySchema",
    "EntityModificationSchema",
    "TreeModificationSchema",
    "DiffASTParseSchema",
    "TokenLogprobSchema",
    "TokenEntropySchema",
    "TokenVelocitySchema",
    "PromptResponseDistributionSchema",
    "EpistemicUncertaintyVectorSchema",
    "TokenEntropyEvaluationSchema",
    "EnergyGradientResidualSchema",
    "RotationalDriftResidualSchema",
    "SCFConvergenceResidualSchema",
    "PhysicalResidualVectorSchema",
    "PhysicalResidualRecordSchema",
    "TaskVectorSchema",
    "ASTDiffVectorSchema",
    "ExecutionTelemetryVectorSchema",
    "MultimodalStateVectorSchema",
    "StateVectorRecordSchema",
    "StandardizerConfigSchema",
    "RollingWindowStatsSchema",
    "StandardizedVectorRecordSchema",
    "TensorCacheConfigSchema",
    "TensorRecordMetadataSchema",
    "PaginatedSliceSchema",
    "TensorCacheMetricsSchema",
    "ChunkGeometrySpecSchema",
    "DatasetPreallocationSpecSchema",
    "PreallocatedStreamerConfigSchema",
    "FragmentationMetricsSchema",
    "StreamedBatchReceiptSchema",
    "DAGNodeSchema",
    "DAGEdgeSchema",
    "RollbackResultSchema",
    "VisualizerNodeLayoutSchema",
    "VisualizerEdgeLayoutSchema",
    "DAGVisualizerStateSchema",
    "JSONLDRegistryPayloadSchema",
    "ProcessMemorySnapshotSchema",
    "RAMTelemetryRecordSchema",
    "RAMGuardrailConfigSchema",
    "RAMGuardrailMetricsSchema",
    "AuditTraceQuerySchema",
    "DaemonConfigSchema",
    "DaemonTelemetryMetricsSchema",
    "ParquetBufferConfigSchema",
    "ParquetBufferMetricsSchema",
]
