"""
CoChem Orchestrator Package.
Provides multi-phase environment gatekeeping, initialization, and deployment pipeline.
"""

from __future__ import annotations

from orchestrator.cochem_setup_phase_1 import (
    DependencyManager,
    FilesystemAudit,
    KernelLimitsAudit,
    OSProfile,
    Phase1AuditReport,
    PhaseStatus,
    ToolchainItem,
    WSL9PMountError,
    audit_filesystem,
    audit_kernel_limits,
    audit_toolchains,
    interrogate_os,
    run_phase_1_audit,
)
from orchestrator.cochem_setup_phase_1 import (
    main as phase_1_main,
)
from orchestrator.cochem_setup_phase_2 import (
    CPUAudit,
    GPUDevice,
    GPUProfile,
    IEEE754PrecisionAudit,
    MemoryAudit,
    Phase2AuditError,
    Phase2AuditReport,
    audit_cpu,
    audit_gpus,
    audit_memory,
    parse_cgroup_cpu_quota,
    parse_cgroup_memory_limit,
    probe_amd_gpus,
    probe_intel_gpus,
    probe_nvidia_gpus,
    resolve_p2_registry_path,
    run_phase_2_audit,
    verify_ieee754_subnormal_precision,
)
from orchestrator.cochem_setup_phase_2 import (
    main as phase_2_main,
)

from orchestrator.cochem_setup_phase_3 import (
    BinaryEngineItem,
    ContainerAudit,
    EngineStatus,
    EngineTrack,
    EngineTrackSummary,
    EnvironmentFingerprint,
    Phase3AuditError,
    Phase3AuditReport,
    audit_all_engines,
    audit_container_sifs,
    audit_single_binary,
    build_track_summaries,
    compute_environment_fingerprint,
    resolve_p3_registry_path,
    run_phase_3_audit,
)
from orchestrator.cochem_setup_phase_3 import (
    main as phase_3_main,
)
from orchestrator.cochem_setup_phase_4 import (
    DynamicVersionWalkingResult,
    DynamicVersionWalkStep,
    IPCSecurityAudit,
    ManifestFilterAudit,
    MendeleevMassRecord,
    Phase4AuditError,
    Phase4AuditReport,
    SiloAuditItem,
    SiloConfig,
    SiloProvisioningError,
    SiloStatus,
    SiloType,
    VersionWalkingError,
    audit_ipc_and_mps_security,
    audit_micro_silos,
    enforce_python_version,
    execute_dynamic_version_walking,
    filter_silos_by_manifest,
    get_default_silo_configs,
    get_native_memory_env_vars,
    get_native_stack_flags,
    get_silo_executable_path,
    inject_silo_stack_and_env_flags,
    load_deployment_manifest,
    provision_micro_silo,
    resolve_p4_registry_path,
    resolve_silo_base_directory,
    run_phase_4_audit,
    scan_local_fallback_binaries,
    verify_mendeleev_authority,
)
from orchestrator.cochem_setup_phase_4 import (
    main as phase_4_main,
)
from orchestrator.cochem_setup_phase_5 import (
    GPUDeviceVRAM,
    MPSControlError,
    MPSDaemonAudit,
    MPSStatus,
    Phase5AuditError,
    Phase5AuditReport,
    VRAMAllocationError,
    VRAMBudgetReport,
    build_pinned_memory_limit_string,
    calculate_vram_budget,
    configure_mps_device_limit,
    discover_mps_binaries,
    enforce_socket_directory_permissions,
    generate_mps_activation_scripts,
    get_current_username,
    inject_mps_environment_variables,
    probe_gpu_devices_vram,
    probe_mps_daemon_status,
    resolve_mps_log_directory,
    resolve_mps_pipe_directory,
    resolve_p5_registry_path,
    run_phase_5_audit,
    start_mps_daemon,
    stop_mps_daemon,
)
from orchestrator.cochem_setup_phase_5 import (
    main as phase_5_main,
)

__all__ = [
    "BinaryEngineItem",
    "CPUAudit",
    "ContainerAudit",
    "DependencyManager",
    "DynamicVersionWalkStep",
    "DynamicVersionWalkingResult",
    "EngineStatus",
    "EngineTrack",
    "EngineTrackSummary",
    "EnvironmentFingerprint",
    "FilesystemAudit",
    "GPUDevice",
    "GPUDeviceVRAM",
    "GPUProfile",
    "IEEE754PrecisionAudit",
    "IPCSecurityAudit",
    "KernelLimitsAudit",
    "MPSControlError",
    "MPSDaemonAudit",
    "MPSStatus",
    "ManifestFilterAudit",
    "MemoryAudit",
    "MendeleevMassRecord",
    "OSProfile",
    "Phase1AuditReport",
    "Phase2AuditError",
    "Phase2AuditReport",
    "Phase3AuditError",
    "Phase3AuditReport",
    "Phase4AuditError",
    "Phase4AuditReport",
    "Phase5AuditError",
    "Phase5AuditReport",
    "PhaseStatus",
    "SiloAuditItem",
    "SiloConfig",
    "SiloProvisioningError",
    "SiloStatus",
    "SiloType",
    "ToolchainItem",
    "VRAMAllocationError",
    "VRAMBudgetReport",
    "VersionWalkingError",
    "WSL9PMountError",
    "audit_all_engines",
    "audit_container_sifs",
    "audit_cpu",
    "audit_filesystem",
    "audit_gpus",
    "audit_ipc_and_mps_security",
    "audit_kernel_limits",
    "audit_memory",
    "audit_micro_silos",
    "audit_single_binary",
    "audit_toolchains",
    "build_pinned_memory_limit_string",
    "build_track_summaries",
    "calculate_vram_budget",
    "compute_environment_fingerprint",
    "configure_mps_device_limit",
    "discover_mps_binaries",
    "enforce_python_version",
    "enforce_socket_directory_permissions",
    "execute_dynamic_version_walking",
    "filter_silos_by_manifest",
    "generate_mps_activation_scripts",
    "get_current_username",
    "get_default_silo_configs",
    "get_native_memory_env_vars",
    "get_native_stack_flags",
    "get_silo_executable_path",
    "inject_mps_environment_variables",
    "inject_silo_stack_and_env_flags",
    "interrogate_os",
    "load_deployment_manifest",
    "parse_cgroup_cpu_quota",
    "parse_cgroup_memory_limit",
    "phase_1_main",
    "phase_2_main",
    "phase_3_main",
    "phase_4_main",
    "phase_5_main",
    "probe_amd_gpus",
    "probe_gpu_devices_vram",
    "probe_intel_gpus",
    "probe_mps_daemon_status",
    "probe_nvidia_gpus",
    "provision_micro_silo",
    "resolve_mps_log_directory",
    "resolve_mps_pipe_directory",
    "resolve_p2_registry_path",
    "resolve_p3_registry_path",
    "resolve_p4_registry_path",
    "resolve_p5_registry_path",
    "resolve_silo_base_directory",
    "run_phase_1_audit",
    "run_phase_2_audit",
    "run_phase_3_audit",
    "run_phase_4_audit",
    "run_phase_5_audit",
    "scan_local_fallback_binaries",
    "start_mps_daemon",
    "stop_mps_daemon",
    "verify_ieee754_subnormal_precision",
    "verify_mendeleev_authority",
]


