"""Lazy core facade preserving public names without circular eager imports."""

from __future__ import annotations

from importlib import import_module

_EXPORTS = {
    "cochem_core_registry_manager": ("cochem_base.core.cochem_core_registry_manager", None),
    "AtomicFileLock": ("cochem_base.core.cochem_core_registry_manager", "AtomicFileLock"),
    "BaseMetadataServer": ("cochem_base.core.cochem_core_registry_manager", "BaseMetadataServer"),
    "BasisSetNotFoundError": (
        "cochem_base.core.cochem_core_registry_manager",
        "BasisSetNotFoundError",
    ),
    "CoChemLockTimeoutError": (
        "cochem_base.core.cochem_core_registry_manager",
        "CoChemLockTimeoutError",
    ),
    "FileLockTimeoutError": (
        "cochem_base.core.cochem_core_registry_manager",
        "FileLockTimeoutError",
    ),
    "FilesystemMetadataServer": (
        "cochem_base.core.cochem_core_registry_manager",
        "FilesystemMetadataServer",
    ),
    "MetadataBackendType": ("cochem_base.core.cochem_core_registry_manager", "MetadataBackendType"),
    "MetadataServerManager": (
        "cochem_base.core.cochem_core_registry_manager",
        "MetadataServerManager",
    ),
    "PostgresMetadataServer": (
        "cochem_base.core.cochem_core_registry_manager",
        "PostgresMetadataServer",
    ),
    "RecordNotFoundError": ("cochem_base.core.cochem_core_registry_manager", "RecordNotFoundError"),
    "RedisMetadataServer": ("cochem_base.core.cochem_core_registry_manager", "RedisMetadataServer"),
    "RegistryCorruptionError": (
        "cochem_base.core.cochem_core_registry_manager",
        "RegistryCorruptionError",
    ),
    "RegistryError": ("cochem_base.core.cochem_core_registry_manager", "RegistryError"),
    "RegistryLockError": ("cochem_base.core.cochem_core_registry_manager", "RegistryLockError"),
    "RegistryLockTimeoutError": (
        "cochem_base.core.cochem_core_registry_manager",
        "RegistryLockTimeoutError",
    ),
    "RegistryManager": ("cochem_base.core.cochem_core_registry_manager", "RegistryManager"),
    "RegistryMissingError": (
        "cochem_base.core.cochem_core_registry_manager",
        "RegistryMissingError",
    ),
    "RegistryParseError": ("cochem_base.core.cochem_core_registry_manager", "RegistryParseError"),
    "SchemaMigrationError": (
        "cochem_base.core.cochem_core_registry_manager",
        "SchemaMigrationError",
    ),
    "_sanitize_path_leakages": (
        "cochem_base.core.cochem_core_registry_manager",
        "_sanitize_path_leakages",
    ),
    "atomic_write_json": ("cochem_base.core.cochem_core_registry_manager", "atomic_write_json"),
    "broadcast_system_config": (
        "cochem_base.core.cochem_core_registry_manager",
        "broadcast_system_config",
    ),
    "default_metadata_manager": (
        "cochem_base.core.cochem_core_registry_manager",
        "default_metadata_manager",
    ),
    "get_active_job": ("cochem_base.core.cochem_core_registry_manager", "get_active_job"),
    "get_default_config_path": (
        "cochem_base.core.cochem_core_registry_manager",
        "get_default_config_path",
    ),
    "hash_environment": ("cochem_base.core.cochem_core_registry_manager", "hash_environment"),
    "interpolate_env_vars": (
        "cochem_base.core.cochem_core_registry_manager",
        "interpolate_env_vars",
    ),
    "is_master_node": ("cochem_base.core.cochem_core_registry_manager", "is_master_node"),
    "list_active_jobs": ("cochem_base.core.cochem_core_registry_manager", "list_active_jobs"),
    "load_system_config": ("cochem_base.core.cochem_core_registry_manager", "load_system_config"),
    "migrate_schema": ("cochem_base.core.cochem_core_registry_manager", "migrate_schema"),
    "nfs_atomic_directory_rename": (
        "cochem_base.core.cochem_core_registry_manager",
        "nfs_atomic_directory_rename",
    ),
    "receive_system_config_broadcast": (
        "cochem_base.core.cochem_core_registry_manager",
        "receive_system_config_broadcast",
    ),
    "register_active_job": ("cochem_base.core.cochem_core_registry_manager", "register_active_job"),
    "remove_active_job": ("cochem_base.core.cochem_core_registry_manager", "remove_active_job"),
    "save_system_config": ("cochem_base.core.cochem_core_registry_manager", "save_system_config"),
    "update_active_job": ("cochem_base.core.cochem_core_registry_manager", "update_active_job"),
    "update_system_config": (
        "cochem_base.core.cochem_core_registry_manager",
        "update_system_config",
    ),
    "AirGapConfig": ("cochem.core.airgap_coordinator", "AirGapConfig"),
    "AirGapCoordinator": ("cochem.core.airgap_coordinator", "AirGapCoordinator"),
    "AirGapViolationError": ("cochem.core.airgap_coordinator", "AirGapViolationError"),
    "TripartiteAirGapCoordinator": (
        "cochem.core.airgap_coordinator",
        "TripartiteAirGapCoordinator",
    ),
    "TripartiteStorageConfig": ("cochem.core.airgap_coordinator", "TripartiteStorageConfig"),
    "get_tier_file_lock": ("cochem.core.airgap_coordinator", "get_tier_file_lock"),
    "SandboxConfig": ("cochem.core.cochem_sandbox", "SandboxConfig"),
    "SandboxContext": ("cochem.core.cochem_sandbox", "SandboxContext"),
    "SandboxExecutionError": ("cochem.core.cochem_sandbox", "SandboxExecutionError"),
    "SandboxSecurityViolationError": (
        "cochem.core.cochem_sandbox",
        "SandboxSecurityViolationError",
    ),
    "CoChemConfigManager": ("cochem.core.config", "CoChemConfigManager"),
    "CoChemRootConfig": ("cochem.core.config", "CoChemRootConfig"),
    "ConfigurationParseError": ("cochem.core.config", "ConfigurationParseError"),
    "CoreConfig": ("cochem.core.config", "CoreConfig"),
    "DatabaseConfig": ("cochem.core.config", "DatabaseConfig"),
    "OrchestrationConfig": ("cochem.core.config", "OrchestrationConfig"),
    "QmMMConfig": ("cochem.core.config", "QmMMConfig"),
    "TelemetryConfig": ("cochem.core.config", "TelemetryConfig"),
    "get_workspace_config": ("cochem.core.config", "get_workspace_config"),
    "FileLock": ("cochem.core.context", "FileLock"),
    "HessianSymmetryError": ("cochem.core.ingestors.protocols", "HessianSymmetryError"),
    "MolecularStructureData": ("cochem.core.ingestors.protocols", "MolecularStructureData"),
    "QCResultsSchema": ("cochem.core.ingestors.protocols", "QCResultsSchema"),
    "QCValidationError": ("cochem.core.ingestors.protocols", "QCValidationError"),
    "SpinContaminationError": ("cochem.core.ingestors.protocols", "SpinContaminationError"),
    "MAX_IPC_PAYLOAD_BYTES": ("cochem.core.ipc.serializer", "MAX_IPC_PAYLOAD_BYTES"),
    "HMACSocketClient": ("cochem.core.ipc.serializer", "HMACSocketClient"),
    "HMACSocketServer": ("cochem.core.ipc.serializer", "HMACSocketServer"),
    "IPCPayloadError": ("cochem.core.ipc.serializer", "IPCPayloadError"),
    "OversizedPayloadError": ("cochem.core.ipc.serializer", "OversizedPayloadError"),
    "PESStore": ("cochem_base.core_engine.cochem_core_pes_store", "PESStore"),
    "SharedMemoryBuffer": ("cochem.core.ipc.serializer", "SharedMemoryBuffer"),
    "TruncatedPayloadError": ("cochem.core.ipc.serializer", "TruncatedPayloadError"),
    "pack_payload": ("cochem.core.ipc.serializer", "pack_payload"),
    "unpack_payload": ("cochem.core.ipc.serializer", "unpack_payload"),
    "MendeleevInvariantError": ("cochem.core.mendeleev_invariants", "MendeleevInvariantError"),
    "CoChemHDF5Manager": ("cochem_base.core.cochem_core_hdf5_manager", "CoChemHDF5Manager"),
    "did_key_to_public_key": ("cochem_base.core.cochem_crypto", "did_key_to_public_key"),
    "public_key_to_did_key": ("cochem_base.core.cochem_crypto", "public_key_to_did_key"),
    "sign_report_payload": ("cochem_base.core.cochem_crypto", "sign_report_payload"),
    "verify_report_payload": ("cochem_base.core.cochem_crypto", "verify_report_payload"),
    "DAGNode": ("cochem_base.core.cochem_provenance", "DAGNode"),
    "get_local_prov_context": ("cochem_base.core.cochem_provenance", "get_local_prov_context"),
    "get_vcs_provenance": ("cochem_base.core.cochem_version", "get_vcs_provenance"),
    "IsotopeStabilityError": ("cochem_base.core.exceptions", "IsotopeStabilityError"),
    "RadiusNotFoundError": ("cochem_base.core.exceptions", "RadiusNotFoundError"),
    "CalculationFidelity": ("cochem_base.core.glossary", "CalculationFidelity"),
    "UnitConversionConstants": ("cochem_base.core.glossary", "UnitConversionConstants"),
    "OFFICIAL_SPDX_LICENSES": ("cochem_base.core.licensing", "OFFICIAL_SPDX_LICENSES"),
    "validate_spdx_license": ("cochem_base.core.licensing", "validate_spdx_license"),
    "collect_hardware_metadata": ("cochem_base.core.metadata", "collect_hardware_metadata"),
    "get_covalent_radius": ("cochem_base.core.metadata", "get_covalent_radius"),
    "get_isotopic_mass": ("cochem_base.core.metadata", "get_isotopic_mass"),
    "NAMESPACE_COCHEM": ("cochem_base.core.models", "NAMESPACE_COCHEM"),
    "CalculationJobPayload": ("cochem_base.core.models", "CalculationJobPayload"),
    "MolecularTopology": ("cochem_base.core.models", "MolecularTopology"),
    "PESPointRecord": ("cochem_base.core.models", "PESPointRecord"),
    "QCResultsRecord": ("cochem_base.core.models", "QCResultsRecord"),
    "get_node_local_scratch_dir": (
        "cochem_base.core_engine.cochem_core_pes_store",
        "get_node_local_scratch_dir",
    ),
    "CoChemRegistry": ("cochem_base.core.cochem_core_registry_manager", "RegistryManager"),
}

__all__ = [
    "cochem_core_registry_manager",
    "AtomicFileLock",
    "BaseMetadataServer",
    "BasisSetNotFoundError",
    "CoChemLockTimeoutError",
    "FileLockTimeoutError",
    "FilesystemMetadataServer",
    "IsotopeStabilityError",
    "MetadataBackendType",
    "MetadataServerManager",
    "PostgresMetadataServer",
    "RecordNotFoundError",
    "RedisMetadataServer",
    "RegistryCorruptionError",
    "RegistryError",
    "RegistryLockError",
    "RegistryLockTimeoutError",
    "RegistryManager",
    "RegistryMissingError",
    "RegistryParseError",
    "SchemaMigrationError",
    "CoChemRegistry",
    "_sanitize_path_leakages",
    "atomic_write_json",
    "broadcast_system_config",
    "default_metadata_manager",
    "get_active_job",
    "get_default_config_path",
    "hash_environment",
    "interpolate_env_vars",
    "is_master_node",
    "list_active_jobs",
    "load_system_config",
    "migrate_schema",
    "nfs_atomic_directory_rename",
    "receive_system_config_broadcast",
    "register_active_job",
    "remove_active_job",
    "save_system_config",
    "update_active_job",
    "update_system_config",
    "CoChemConfigManager",
    "CoChemRootConfig",
    "ConfigurationParseError",
    "CoreConfig",
    "DatabaseConfig",
    "OrchestrationConfig",
    "QmMMConfig",
    "TelemetryConfig",
    "get_workspace_config",
    "SandboxConfig",
    "SandboxContext",
    "SandboxExecutionError",
    "SandboxSecurityViolationError",
    "AirGapConfig",
    "AirGapCoordinator",
    "AirGapViolationError",
    "TripartiteAirGapCoordinator",
    "TripartiteStorageConfig",
    "get_tier_file_lock",
    "FileLock",
    "HMACSocketClient",
    "HMACSocketServer",
    "IPCPayloadError",
    "MAX_IPC_PAYLOAD_BYTES",
    "OversizedPayloadError",
    "PESStore",
    "SharedMemoryBuffer",
    "TruncatedPayloadError",
    "pack_payload",
    "unpack_payload",
    "HessianSymmetryError",
    "MolecularStructureData",
    "QCResultsSchema",
    "QCValidationError",
    "SpinContaminationError",
    "MendeleevInvariantError",
    "CoChemHDF5Manager",
    "QCResultsRecord",
    "MolecularTopology",
    "PESPointRecord",
    "UnitConversionConstants",
    "IsotopeStabilityError",
    "RadiusNotFoundError",
    "OFFICIAL_SPDX_LICENSES",
    "validate_spdx_license",
    "get_isotopic_mass",
    "get_covalent_radius",
    "collect_hardware_metadata",
    "DAGNode",
    "get_local_prov_context",
    "did_key_to_public_key",
    "public_key_to_did_key",
    "sign_report_payload",
    "verify_report_payload",
    "get_vcs_provenance",
    "CalculationFidelity",
    "CalculationJobPayload",
    "NAMESPACE_COCHEM",
    "get_node_local_scratch_dir",
]


def __getattr__(name: str):
    if name not in _EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, member = _EXPORTS[name]
    module = import_module(module_name)
    value = module if member is None else getattr(module, member)
    globals()[name] = value
    return value
