"""CoChem-TOPOS Topology Package.

Provides graph-based molecular connectivity, resonance protection scaling,
non-covalent complex cleavage, conformer deduplication funnel, and jiggle-quench arbitration.
"""

from topology.cochem_topos_crusher import (
    ConformerCandidate,
    CRESTConformerEngine,
    DeduplicatedConformerRecord,
    DeduplicationRecord,
    DeduplicationVerdict,
    DipoleMoment,
    EnsembleDeduplicationReport,
    GOATConformerEngine,
    KDTreeCoordinateFilter,
    MassWeightedEckartRMSD,
    MemmapIsomerBuffer,
    RotationalConstants,
    RotationalSieve,
    TopologyCrusher,
    ToposCrusher,
    align_to_eckart_frame,
    compute_chiral_volumes,
    compute_dipole_moment,
    compute_distance_filtered_coulomb_matrix,
    compute_dof_scaled_rmsd_threshold,
    compute_mass_weighted_eckart_rmsd,
    compute_rotational_constants,
    evaluate_bounding_box_filter,
    evaluate_coulomb_eigenspectrum,
    evaluate_molsym_symmetry_filter,
    evaluate_networkx_connectivity_hash,
    is_enantiomer_pair,
)
from topology.cochem_topos_graph import (
    COVALENT_RADII,
    RESONANCE_PROTECTION_SCALE,
    MonomerSeed,
    TopologyAnalysisResult,
    TopologyGraphEngine,
    analyze_molecular_graph,
    generate_chemical_formula,
    get_covalent_radius,
    parse_xyz_file,
    parse_xyz_string,
)
from topology.cochem_topos_wiggle import (
    JiggleQuenchArbiter,
    JiggleQuenchConfig,
    JiggleQuenchResult,
    arbitrate_basin_merge,
    execute_lightning_quench,
    jiggle_perturb_pair,
)

__all__ = [
    # Graph Engine exports
    "TopologyGraphEngine",
    "TopologyAnalysisResult",
    "MonomerSeed",
    "analyze_molecular_graph",
    "parse_xyz_string",
    "parse_xyz_file",
    "generate_chemical_formula",
    "get_covalent_radius",
    "COVALENT_RADII",
    "RESONANCE_PROTECTION_SCALE",
    # Deduplication Crusher exports
    "TopologyCrusher",
    "ToposCrusher",
    "RotationalSieve",
    "KDTreeCoordinateFilter",
    "MassWeightedEckartRMSD",
    "GOATConformerEngine",
    "CRESTConformerEngine",
    "ConformerCandidate",
    "RotationalConstants",
    "DipoleMoment",
    "DeduplicationVerdict",
    "DeduplicationRecord",
    "DeduplicatedConformerRecord",
    "EnsembleDeduplicationReport",
    "MemmapIsomerBuffer",
    "compute_rotational_constants",
    "compute_dipole_moment",
    "align_to_eckart_frame",
    "compute_mass_weighted_eckart_rmsd",
    "is_enantiomer_pair",
    "compute_chiral_volumes",
    "evaluate_bounding_box_filter",
    "evaluate_molsym_symmetry_filter",
    "evaluate_networkx_connectivity_hash",
    "compute_distance_filtered_coulomb_matrix",
    "evaluate_coulomb_eigenspectrum",
    "compute_dof_scaled_rmsd_threshold",
    # Jiggle-Quench Subroutine exports
    "JiggleQuenchConfig",
    "JiggleQuenchResult",
    "JiggleQuenchArbiter",
    "jiggle_perturb_pair",
    "execute_lightning_quench",
    "arbitrate_basin_merge",
]
