#!/usr/bin/env python3
"""
CoChem-BASE Stage 0.2b: HPC Login-Node Prober & SLURM Configurator
Safely maps the execution pathways on a high-performance computing cluster
without violating login-node policies. Configures SLURM routing rules.
"""

import atexit
import json
import logging
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Optional

try:
    import psutil
except ImportError:
    psutil = None


logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger("CoChem-HPCSetup")

try:
    from core_engine.cochem_core_subprocess_broker import safe_subprocess_run
except ImportError:
    safe_subprocess_run = None


def cleanup_zombies() -> None:
    """Ensure zombie process sweeping via psutil."""
    if psutil is None:
        return
    try:
        current_process = psutil.Process(os.getpid())
        children = current_process.children(recursive=True)
        if not children:
            return
        for child in children:
            try:
                child.terminate()
            except psutil.NoSuchProcess:
                pass
        gone, alive = psutil.wait_procs(children, timeout=3)
        for p in alive:
            try:
                p.kill()
            except psutil.NoSuchProcess:
                pass
    except Exception as e:
        logger.debug(f"Zombie sweep failed: {e}")

atexit.register(cleanup_zombies)


from cochem_base.config_loader import get_artifact_dir, resolve_executable, load_system_config, update_config
from core_engine.cochem_core_registry_schema import CoChemConfig


def locate_artifact_dir() -> Path:
    """Locates the pre-established CoChem_Artifacts directory."""
    artifact_dir = get_artifact_dir()
    if not artifact_dir.exists():
        logger.error("Air-Gap directory (CoChem_Artifacts) not found.")
        logger.error("Please run Stage 0.2a (interact_codespaces.py) or base setup first.")
        sys.exit(1)
    return artifact_dir


def check_slurm_presence() -> bool:
    """Executes a lightweight query to detect the SLURM scheduler without heavy compute."""
    logger.info("Probing for SLURM scheduler (sbatch)...")
    sbatch_bin = resolve_executable(env_var="SBATCH_CMD", candidates=("sbatch",))
    
    if not shutil.which(sbatch_bin):
        logger.warning(f"SLURM not found on this node. Could not resolve {sbatch_bin}")
        return False
        
    try:
        if safe_subprocess_run is not None:
            result = safe_subprocess_run([sbatch_bin, "--version"], timeout=10.0, check=True)
        else:
            result = subprocess.run([sbatch_bin, "--version"], capture_output=True, text=True, timeout=10.0, check=True)
        
        logger.info(f"SLURM detected: {result.stdout.strip()}")
        return True
    except subprocess.TimeoutExpired as e:
        logger.warning(f"SLURM check timed out: {e}")
        return False
    except subprocess.CalledProcessError as e:
        logger.warning(f"SLURM check failed with exit code {e.returncode}: {e}")
        return False
    except FileNotFoundError:
        logger.warning("SLURM executable not found during execution.")
        return False
    except Exception as e:
        logger.error(f"Unexpected error during SLURM check: {e}")
        return False


def generate_sbatch_template(artifact_dir: Path, modules: str) -> str:
    """Generates a standardized .sbatch execution template for the pipeline to consume."""
    template_dir = artifact_dir / "Registry" / "Templates"
    template_dir.mkdir(parents=True, exist_ok=True)
    template_path = template_dir / "cochem_standard.sbatch"

    sbatch_content = f"""#!/bin/bash
#SBATCH --job-name=CoChem_Job
#SBATCH --nodes=1
#SBATCH --ntasks-per-node={{n_cores}}
#SBATCH --mem={{mem_mb}}M
#SBATCH --time={{time_limit}}
#SBATCH --output={{log_dir}}/%x_%j.out
#SBATCH --error={{log_dir}}/%x_%j.err

# ==========================================
# CoChem HPC Execution Template
# Automatically Generated by Stage 0.2b
# ==========================================

# Load User-Specified Modules
{modules}

# Execute Payload
echo "🚀 Starting CoChem HPC Job on host: $HOSTNAME"
{{payload_command}}
echo "✅ CoChem HPC Job Completed."
"""
    with open(template_path, 'w', encoding="utf-8") as f:
        f.write(sbatch_content)
    logger.info(f"Standard SLURM template generated at: {template_path}")
    return str(template_path)


def update_golden_registry(artifact_dir: Path, template_path: str, modules: str) -> None:
    """Updates the Golden Registry to route future calculations to SLURM."""
    registry_path = artifact_dir / "Registry" / "cochem_system_config.json"
    
    registry_path.parent.mkdir(parents=True, exist_ok=True)

    try:
        registry = load_system_config(registry_path)
    except (FileNotFoundError, ValueError) as e:
        logger.warning(f"Failed to load existing registry: {e}. Creating new default config.")
        registry = CoChemConfig.create_default()

    registry.hpc.scheduler = "slurm"
    registry.hpc.sbatch_template = template_path

    if registry.execution is None:
        registry.execution = {}
    
    registry.execution["default_engine"] = "sbatch"
    registry.execution["status"] = "slurm_ready"
    registry.execution["module_loads"] = modules

    update_config(registry, registry_path)

    logger.info("Golden Registry updated with strict HPC SLURM routing rules.")


def run_hpc_setup() -> None:
    logger.info("=======================================================")
    logger.info(" CoChem-BASE: HPC Login-Node Prober & SLURM Configurator")
    logger.info("=======================================================\n")

    artifact_dir = locate_artifact_dir()

    if not check_slurm_presence():
        logger.warning("Halting HPC configuration. Target is not a SLURM submit node.")
        sys.exit(0)

    if len(sys.argv) > 1:
        modules = "\n".join(f"module load {mod}" for mod in sys.argv[1:])
    else:
        modules = "module load openmpi\nmodule load orca"
        logger.info(f"No custom modules provided. Using default:\n{modules}")

    template_path = generate_sbatch_template(artifact_dir, modules)
    update_golden_registry(artifact_dir, template_path, modules)

    logger.info("Cloud-to-Cluster (C2C) HPC matrix successfully configured. Ready for dispatch.")


if __name__ == "__main__":
    run_hpc_setup()
