# CoChem AI Package
"""
CoChem-BASE: Artificial Intelligence, Inference Engine, Hardware Safety,
and Context Compression Subsystem.
"""

from cochem_core.ai.context_compression import (
    DEFAULT_CHUNK_MAX_CHARS,
    DEFAULT_TENSOR_THRESHOLD,
    DEFAULT_TRACEBACK_MAX_LINES,
    ContextCompressor,
    HDF5PointerModel,
    MarkdownChunkModel,
    TensorSummaryModel,
    TracebackSummaryModel,
    chunk_literature_by_headers,
    chunk_markdown_by_headers,
    compress_tensors_for_llm,
    create_hdf5_pointer,
    dumps_rfc8259,
    extract_hdf5_pointers,
    is_hdf5_pointer,
    loads_rfc8259,
    parse_hdf5_pointer,
    resolve_hdf5_pointer,
    sanitize_numerical_values,
    strip_ansi_escape_codes,
    to_rfc8259_json,
    truncate_traceback,
)
from cochem_core.ai.lttb_downsampling import (
    DEFAULT_LTTB_THRESHOLD,
    LTTBDownsampler,
    LTTBResult,
    lttb_downsample,
    lttb_downsample_1d,
    lttb_downsample_indices,
    lttb_downsample_xy,
)

from cochem_core.ai.template_engine import (
    APS_UNIT_MAPPINGS,
    DEFAULT_ROLE_PROMPT,
    H5DataInjector,
    InjectedDataSummary,
    LaTeXFormatter,
    LaTeXFormattingOptions,
    PayloadBuilder,
    PromptPayload,
    SYSTEMIC_COMMAND,
    SYSTEMIC_COMMAND_AIRGAP,
    TemplateEngine,
    build_system_prompt,
    create_payload,
    enforce_latex_siunitx,
    extract_h5_float64_dataset,
    format_siunitx_angle,
    format_siunitx_num,
    format_siunitx_qty,
    inject_landscape_data,
    resolve_landscape_h5_file,
)

__all__ = [
    "APS_UNIT_MAPPINGS",
    "ContextCompressor",
    "DEFAULT_CHUNK_MAX_CHARS",
    "DEFAULT_LTTB_THRESHOLD",
    "DEFAULT_ROLE_PROMPT",
    "DEFAULT_TENSOR_THRESHOLD",
    "DEFAULT_TRACEBACK_MAX_LINES",
    "H5DataInjector",
    "HDF5PointerModel",
    "InjectedDataSummary",
    "LTTBDownsampler",
    "LTTBResult",
    "LaTeXFormatter",
    "LaTeXFormattingOptions",
    "MarkdownChunkModel",
    "PayloadBuilder",
    "PromptPayload",
    "SYSTEMIC_COMMAND",
    "SYSTEMIC_COMMAND_AIRGAP",
    "TemplateEngine",
    "TensorSummaryModel",
    "TracebackSummaryModel",
    "build_system_prompt",
    "chunk_literature_by_headers",
    "chunk_markdown_by_headers",
    "compress_tensors_for_llm",
    "create_hdf5_pointer",
    "create_payload",
    "dumps_rfc8259",
    "enforce_latex_siunitx",
    "extract_h5_float64_dataset",
    "extract_hdf5_pointers",
    "format_siunitx_angle",
    "format_siunitx_num",
    "format_siunitx_qty",
    "inject_landscape_data",
    "is_hdf5_pointer",
    "loads_rfc8259",
    "lttb_downsample",
    "lttb_downsample_1d",
    "lttb_downsample_indices",
    "lttb_downsample_xy",
    "parse_hdf5_pointer",
    "resolve_hdf5_pointer",
    "resolve_landscape_h5_file",
    "sanitize_numerical_values",
    "strip_ansi_escape_codes",
    "to_rfc8259_json",
    "truncate_traceback",
]

