"""Convenience re-exports for TOPOS exceptions."""

from __future__ import annotations

from cochem.topos.exceptions import (
    ToposError,
    TopologyError,
    StericClashError,
    IsomorphismMismatchError,
    ChiralityAssignmentError,
    CoChemToposException,
    SymmetryPerceptionError,
    PharmacophoreExtractionError,
    IsotopeResolutionError,
    TPSACalculationError,
    ResonanceEnumerationError,
    GraphSparsificationError,
    SolventBuilderError,
    TopologicalCanonicalizationError,
    MalformedRecordError,
    UnparameterizedAtomError,
    BondPerceptionError,
    ParsingAirGapError,
    TopologyDiffError,
    FragmentationError,
    FingerprintGenerationError,
    ScaffoldMatchingError,
    BioisostereNotFoundError,
    GeometricPlausibilityError,
    PyMOLExportError,
    CoordinationPerceptionError,
    SanitizationError,
)

__all__ = [
    "ToposError",
    "TopologyError",
    "StericClashError",
    "IsomorphismMismatchError",
    "ChiralityAssignmentError",
    "CoChemToposException",
    "SymmetryPerceptionError",
    "PharmacophoreExtractionError",
    "IsotopeResolutionError",
    "TPSACalculationError",
    "ResonanceEnumerationError",
    "GraphSparsificationError",
    "SolventBuilderError",
    "TopologicalCanonicalizationError",
    "MalformedRecordError",
    "UnparameterizedAtomError",
    "BondPerceptionError",
    "ParsingAirGapError",
    "TopologyDiffError",
    "FragmentationError",
    "FingerprintGenerationError",
    "ScaffoldMatchingError",
    "BioisostereNotFoundError",
    "GeometricPlausibilityError",
    "PyMOLExportError",
    "CoordinationPerceptionError",
    "SanitizationError",
]
