#!/usr/bin/env python3
"""
CoChem-BASE Stage 0.2b: HPC Login-Node Prober & SLURM Configurator
Safely maps the execution pathways on a high-performance computing cluster
without violating login-node policies. Configures SLURM routing rules.
"""

import os
import sys
import json
import shutil
import subprocess
import logging
from pathlib import Path
from cochem_base.config_loader import get_artifact_dir

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger("CoChem-HPCSetup")

try:
    from core_engine.cochem_core_subprocess_broker import safe_subprocess_run
except ImportError:
    safe_subprocess_run = None


def locate_artifact_dir() -> Path:
    """Locates the pre-established CoChem_Artifacts directory."""
    artifact_dir = get_artifact_dir()
    if not artifact_dir.exists():
        logger.error("Air-Gap directory (CoChem_Artifacts) not found.")
        logger.error("Please run Stage 0.2a (interact_codespaces.py) or base setup first.")
        sys.exit(1)
    return artifact_dir


def check_slurm_presence() -> bool:
    """Executes a lightweight query to detect the SLURM scheduler without heavy compute."""
    logger.info("Probing for SLURM scheduler (sbatch)...")
    sbatch_bin = shutil.which("sbatch")
    if sbatch_bin:
        logger.info(f"SLURM detected at: {sbatch_bin}")
        return True
    try:
        if safe_subprocess_run:
            result = safe_subprocess_run(["sbatch", "--version"], timeout=10.0, check=True)
        else:
            result = subprocess.run(["sbatch", "--version"], capture_output=True, text=True, timeout=10.0, check=True)
        logger.info(f"SLURM detected: {result.stdout.strip()}")
        return True
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired, FileNotFoundError):
        logger.warning("SLURM not found on this node. Execution will default to local subprocess.")
        return False


def generate_sbatch_template(artifact_dir: Path, modules: str) -> str:
    """Generates a standardized .sbatch execution template for the pipeline to consume."""
    template_dir = artifact_dir / "Registry" / "Templates"
    template_dir.mkdir(parents=True, exist_ok=True)
    template_path = template_dir / "cochem_standard.sbatch"

    sbatch_content = f"""#!/bin/bash
#SBATCH --job-name=CoChem_Job
#SBATCH --nodes=1
#SBATCH --ntasks-per-node={{n_cores}}
#SBATCH --mem={{mem_mb}}M
#SBATCH --time={{time_limit}}
#SBATCH --output={{log_dir}}/%x_%j.out
#SBATCH --error={{log_dir}}/%x_%j.err

# ==========================================
# CoChem HPC Execution Template
# Automatically Generated by Stage 0.2b
# ==========================================

# Load User-Specified Modules
{modules}

# Execute Payload
echo "🚀 Starting CoChem HPC Job on host: $HOSTNAME"
{{payload_command}}
echo "✅ CoChem HPC Job Completed."
"""
    with open(template_path, 'w', encoding="utf-8") as f:
        f.write(sbatch_content)
    logger.info(f"Standard SLURM template generated at: {template_path}")
    return str(template_path)


def update_golden_registry(artifact_dir: Path, template_path: str, modules: str) -> None:
    """Updates the Golden Registry to route future calculations to SLURM."""
    registry_path = artifact_dir / "Registry" / "cochem_system_config.json"

    if registry_path.exists():
        with open(registry_path, 'r', encoding="utf-8") as f:
            try:
                registry = json.loads(f.read())
            except json.JSONDecodeError:
                registry = {}
    else:
        registry = {}

    registry.setdefault("hpc", {})
    registry["hpc"]["status"] = "slurm_ready"
    registry["hpc"]["scheduler"] = "slurm"
    registry["hpc"]["module_loads"] = modules
    registry["hpc"]["template_path"] = template_path

    registry.setdefault("execution", {})
    registry["execution"]["default_engine"] = "sbatch"

    with open(registry_path, 'w', encoding="utf-8") as f:
        json.dump(registry, f, indent=4)

    logger.info("Golden Registry updated with strict HPC SLURM routing rules.")


def run_hpc_setup() -> None:
    logger.info("=======================================================")
    logger.info(" CoChem-BASE: HPC Login-Node Prober & SLURM Configurator")
    logger.info("=======================================================\n")

    artifact_dir = locate_artifact_dir()

    if not check_slurm_presence():
        logger.warning("Halting HPC configuration. Target is not a SLURM submit node.")
        sys.exit(0)

    if len(sys.argv) > 1:
        modules = "\n".join(f"module load {mod}" for mod in sys.argv[1:])
    else:
        modules = "module load openmpi\nmodule load orca"
        logger.info(f"No custom modules provided. Using default:\n{modules}")

    template_path = generate_sbatch_template(artifact_dir, modules)
    update_golden_registry(artifact_dir, template_path, modules)

    logger.info("Cloud-to-Cluster (C2C) HPC matrix successfully configured. Ready for dispatch.")


if __name__ == "__main__":
    run_hpc_setup()