#!/usr/bin/env python3
"""
CoChem-BASE Stage 0.2b: HPC Login-Node Prober & SLURM Configurator
Safely maps the execution pathways on a high-performance computing cluster
without violating login-node policies. Configures SLURM routing rules.
"""

import os
import sys
import json
import subprocess
from pathlib import Path

def locate_artifact_dir() -> Path:
    """Locates the pre-established CoChem_Artifacts directory."""
    artifact_dir = Path.home() / "CoChem_Artifacts"
    if not artifact_dir.exists():
        print("❌ FATAL: Air-Gap directory (CoChem_Artifacts) not found.")
        print("Please run Stage 0.2a (interact_codespaces.py) or base setup first.")
        sys.exit(1)
    return artifact_dir

def check_slurm_presence() -> bool:
    """Executes a lightweight query to detect the SLURM scheduler without heavy compute."""
    print("🔍 Probing for SLURM scheduler (sbatch)...")
    try:
        result = subprocess.run(
            ["which", "sbatch"], 
            stdout=subprocess.PIPE, 
            stderr=subprocess.PIPE, 
            text=True,
            check=True
        )
        print(f"✅ SLURM detected at: {result.stdout.strip()}")
        return True
    except subprocess.CalledProcessError:
        print("⚠️ SLURM not found on this node. Execution will default to local subprocess.")
        return False

def generate_sbatch_template(artifact_dir: Path, modules: str) -> str:
    """Generates a standardized .sbatch execution template for the pipeline to consume."""
    template_dir = artifact_dir / "Registry" / "Templates"
    template_dir.mkdir(parents=True, exist_ok=True)
    template_path = template_dir / "cochem_standard.sbatch"

    sbatch_content = f"""#!/bin/bash
#SBATCH --job-name=CoChem_Job
#SBATCH --nodes=1
#SBATCH --ntasks-per-node={{n_cores}}
#SBATCH --mem={{mem_mb}}M
#SBATCH --time={{time_limit}}
#SBATCH --output={{log_dir}}/%x_%j.out
#SBATCH --error={{log_dir}}/%x_%j.err

# ==========================================
# CoChem HPC Execution Template
# Automatically Generated by Stage 0.2b
# ==========================================

# Load User-Specified Modules
{modules}

# Execute Payload
echo "🚀 Starting CoChem HPC Job on host: $HOSTNAME"
{{payload_command}}
echo "✅ CoChem HPC Job Completed."
"""
    with open(template_path, 'w') as f:
        f.write(sbatch_content)
    print(f"✅ Standard SLURM template generated at: {template_path}")
    return str(template_path)

def update_golden_registry(artifact_dir: Path, template_path: str, modules: str):
    """Updates the Golden Registry to route future calculations to SLURM."""
    registry_path = artifact_dir / "Registry" / "cochem_system_config.json"
    
    if registry_path.exists():
        with open(registry_path, 'r') as f:
            try:
                registry = json.load(f)
            except json.JSONDecodeError:
                registry = {}
    else:
        registry = {}

    # Establish the HPC routing block
    registry.setdefault("hpc", {})
    registry["hpc"]["status"] = "slurm_ready"
    registry["hpc"]["scheduler"] = "slurm"
    registry["hpc"]["module_loads"] = modules
    registry["hpc"]["template_path"] = template_path
    
    # Override execution default to prevent local CPU overload on the login node
    registry.setdefault("execution", {})
    registry["execution"]["default_engine"] = "sbatch"

    with open(registry_path, 'w') as f:
        json.dump(registry, f, indent=4)
        
    print(f"✅ Golden Registry updated with strict HPC SLURM routing rules.")

def run_hpc_setup():
    print("=======================================================")
    print(" CoChem-BASE: HPC Login-Node Prober & SLURM Configurator")
    print("=======================================================\n")
    
    artifact_dir = locate_artifact_dir()
    
    if not check_slurm_presence():
        print("🛑 Halting HPC configuration. Target is not a SLURM submit node.")
        sys.exit(0)

    # Allow custom module parsing via CLI, otherwise use common defaults
    if len(sys.argv) > 1:
        modules = "\n".join(f"module load {mod}" for mod in sys.argv[1:])
    else:
        modules = "module load openmpi\nmodule load orca"
        print(f"ℹ️ No custom modules provided. Using default:\n{modules}")

    template_path = generate_sbatch_template(artifact_dir, modules)
    update_golden_registry(artifact_dir, template_path, modules)
    
    print("\n✅ Cloud-to-Cluster (C2C) HPC matrix successfully configured. Ready for dispatch.")

if __name__ == "__main__":
    run_hpc_setup()