"""CoChem Mobile 2D Organic & Inorganic Complex Synthesis Platform.

Zero-Mock implementation of touch-optimized 2D sketcher, RDKit conformer engine,
and Inorganic Complex Generator UI (SRS Chunk 06).
"""

from __future__ import annotations

from cochem.mobile import assembly
from cochem.mobile.conformer_engine import generate_3d_conformer
from cochem.mobile.inorganic import (
    ChelateAssembler,
    ComplexSummaryCard,
    CoordinateAssembler,
    CoordinationGeometry,
    CoordinationPolyhedron,
    DonorAtom,
    HDF5InorganicSerializer,
    InorganicAirGapClient,
    InorganicAssemblyEngine,
    InorganicAtom3D,
    InorganicBondRecord,
    InorganicBuilderScreen,
    InorganicBuilderWidget,
    InorganicComplex,
    InorganicComplexSchema,
    IsomerPickerWidget,
    IsomerResolver,
    JSONInorganicSerializer,
    Ligand,
    LigandBudgetWidget,
    LigandLibrary,
    LigandSelectorDialog,
    MetalCategory,
    MetalCenter,
    PolyhedronTemplateRegistry,
    SQLiteInorganicStore,
    calculate_formula_weight,
    complex_to_schema,
    get_polyhedron_coordination_number,
)
from cochem.mobile.rdkit_bridge import (
    AtomCoordinate3DRecord,
    ConformerEmbeddingError,
    InvalidSmilesError,
    RDKit3DResult,
    Smiles3DConformerEngine,
    generate_deterministic_3d_coordinates,
    relax_geometry_and_calculate_energy,
    smiles_to_3d,
    smiles_to_3d_async,
    validate_and_sanitize_smiles,
)
from cochem.mobile.schemas import (
    AtomCoordinate2D,
    AtomCoordinate3D,
    Conformer3DResultSchema,
    SketcherPayloadSchema,
    ValenceValidationResultSchema,
)
from cochem.mobile.sketcher_widget import SketcherWidget

__all__ = [
    "assembly",
    "AtomCoordinate2D",
    "AtomCoordinate3D",
    "AtomCoordinate3DRecord",
    "ChelateAssembler",
    "ComplexSummaryCard",
    "Conformer3DResultSchema",
    "ConformerEmbeddingError",
    "CoordinateAssembler",
    "CoordinationGeometry",
    "CoordinationPolyhedron",
    "DonorAtom",
    "HDF5InorganicSerializer",
    "InorganicAirGapClient",
    "InorganicAssemblyEngine",
    "InorganicAtom3D",
    "InorganicBondRecord",
    "InorganicBuilderScreen",
    "InorganicBuilderWidget",
    "InorganicComplex",
    "InorganicComplexSchema",
    "InvalidSmilesError",
    "IsomerPickerWidget",
    "IsomerResolver",
    "JSONInorganicSerializer",
    "Ligand",
    "LigandBudgetWidget",
    "LigandLibrary",
    "LigandSelectorDialog",
    "MetalCategory",
    "MetalCenter",
    "PolyhedronTemplateRegistry",
    "RDKit3DResult",
    "SQLiteInorganicStore",
    "SketcherPayloadSchema",
    "SketcherWidget",
    "Smiles3DConformerEngine",
    "ValenceValidationResultSchema",
    "calculate_formula_weight",
    "complex_to_schema",
    "generate_3d_conformer",
    "generate_deterministic_3d_coordinates",
    "get_polyhedron_coordination_number",
    "relax_geometry_and_calculate_energy",
    "smiles_to_3d",
    "smiles_to_3d_async",
    "validate_and_sanitize_smiles",
]
